name: AutoPublish

on:
  push:
    tags:
      - v*
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # prepare python env
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install twine wheel

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
